apriltag:
  remappings:
    image_rect: /head_front_camera/rgb/image_raw
  parameters:
    image_transport: compressed
    family: 16h5
    size: 0.0375 # tag size without the puter white pixel ring (1px=0.625cm)
    pose_estimation_method: "pnp"
    tag:
      ids: [0,1,2,3,4,5]
      frames: [tag0_top,tag1_front,tag2_left,tag3_right,tag4_back,tag5_bottom]

head_follower:
  remappings:
    joint_trajectory: /head_controller/joint_trajectory
    camera_info: /head_front_camera/rgb/camera_info
  parameters:
    timer_period_sec: 0.1
    pan_joint_name: head_1_joint
    tilt_joint_name: head_2_joint
    control_gain: 0.001
    smoothing_factor: 0.33 # Freddy's magic number

rviz:
  launch_delay_sec: 2.0
  config_file: remote.rviz