apriltag_params:
  image_transport: raw
  family: 16h5
  size: 0.0375
  pose_estimation_method: "pnp"
  tag:
    ids: [0,1,2,3,4,5]
    frames: [tag0_top,tag1_front,tag2_left,tag3_right,tag4_back,tag5_bottom]

use_sim_time: true
spawn_cube: true
cube_pose:
  x: 1.0
  y: 0.0
  z: 1.0
  R: 0.1
  P: 0.1
  Y: 0.1

annotator:
  enabled: true
  image_raw: /image_raw
  detections: /detections
  image_annotated: /image_annotated
